### PR TITLE
Update detailed-guide.md

### PR DESCRIPTION
**Pull request by Despire**

### CODE REVIEW

**Review by cloudziu — APPROVED** [review]
LGTM 👍 @JKBGIT1 so now we can trigger update docs with a command in comment, correct?

**Comment by bernardhalas** [comment]
We should be more careful with PRs and their reviews. There are still references to old API in the docs.

**Review by bernardhalas — CHANGES_REQUESTED** [review]
There are still references to old API in:
`docs/contributing/local-testing.md` and
`docs/storage/storage-solution.md`

**Comment by cloudziu** [comment]
hmmm, good point. Initially, I reviewed only the changes present in the PR itself

**Review by bernardhalas — APPROVED** [review]

**Pull request merged**
