### PR TITLE
Revert "Feat/render yaml from manifests in release"

### PR DESCRIPTION
**Pull request by JKBGIT1**
Reverts berops/claudie#987

I was the one, who proposed waiting for merging this changes to master, before release will happen. However I forgot about that and accidentally merged it. That's the reason behind opening this PR.

### CODE REVIEW

**Comment by MarioUhrik** [comment]
How about we just do a release then? It doesn't make sense for me to revert this.
Not sure what you guys think.
@Despire ?

**Comment by Despire** [comment]
there haven't been any changes since the last release, unless I can merge the cilium PR (which I planned anyways) and make a release

**Comment by JKBGIT1** [comment]
@Despire so, your opinion is to close this PR and just wait for a Cilium PR merge, right?

**Comment by Despire** [comment]
>@Despire so, your opinion is to close this PR and just wait for a Cilium PR merge, right?

Yes.

**Comment by JKBGIT1** [comment]
Conclusion:

This PR is closed, because we made a release.

**Pull request closed without merging**
