### PR TITLE
bugfix: re-fix ansible issue with apt

### LINKED ISSUE #524: Ansible apt occasionally fails
```
8:11AM INF ../go/services/builder/serviceCaller.go:141 > Calling BuildInfrastructure on terraformer for project Scenario-1 module=builder
8:13AM INF ../go/services/builder/serviceCaller.go:163 > Calling InstallVPN on ansibler for project Scenario-1 module=builder
8:42AM INF ../go/services/builder/serviceCaller.go:168 > Calling InstallNodeRequirements on ansibler for project Scenario-1 module=builder
```
One of the playbooks was retrying for about 30 min until it get into working state. The cause of this was ansible `apt` module witch tends to occasionally fail while getting the lock file and/or while connecting to repositories. I've encountered a 30min ansible play:
 - On first run three nodes failed
 - On second run two node failed
 - On third and fourth a single node
The 5th run executed without issues.  

Example logs:
```
fatal: [w-oci-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.8"}, "changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 1246 (apt)"}
```

```
fatal: [m-oci-1]: FAILED! => {"cache_update_time": 1673598211, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'net-tools=1.60+git20180626.aebd88e-1ubuntu1'' failed: E: Failed to fetch http://eu-frankfurt-1-ad-2.clouds.archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb  Connection failed [IP: 91.189.91.122 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://eu-frankfurt-1-ad-2.clouds.archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb  Connection failed [IP: 91.189.91.122 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://eu-frankfurt-1-ad-2.clouds.archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb  Connection failed [IP: 91.189.91.122 80]", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  net-tools\n0 upgraded, 1 newly installed, 0 to remove and 63 not upgraded.\nNeed to get 196 kB of archives.\nAfter this operation, 864 kB of additional disk space will be used.\nErr:1 http://eu-frankfurt-1-ad-2.clouds.archive.ubuntu.com/ubuntu focal/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1ubuntu1\n  Connection failed [IP: 91.189.91.122 80]\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  net-tools", "0 upgraded, 1 newly installed, 0 to remove and 63 not upgraded.", "Need to get 196 kB of archives.", "After this operation, 864 kB of additional disk space will be used.", "Err:1 http://eu-frankfurt-1-ad-2.clouds.archive.ubuntu.com/ubuntu focal/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1ubuntu1", "  Connection failed [IP: 91.189.91.122 80]"]}
```

Eventually, after few retries in ansibler this will run with success, but it extends the deployment time quite significantly. What I propose is to add a retry to the `apt` tasks in ansibler. This way it won't repeat the whole play for all the nodes and can shorten the deployment time in some cases.

### PR DESCRIPTION
**Pull request by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf**
* gather facts for playbook - this was the crux of the issue due to which #538 didn't work as planned and had to be reverted
* re-enable the `kill_unattended_upgrades.yml` task in the WG playbook
* fixes #524

### CODE REVIEW

**Review by MiroslavRepka — APPROVED** [review]
LGTM, I don't see any issues there. Please test it thoroughly before merging.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> LGTM, I don't see any issues there. Please test it thoroughly before merging.

Thanks for the review.

I have already tested the WG playbook on the exact same Ubuntu 22.04 GCP image that is listed in example input manifests, before landing this PR.
With properly gathered facts the conditional check for Ubuntu works as intended.

We could be having discussions on other topics, though, such as:
* we should make a note somewhere that Claudie sets up the default-image nodes without unattended upgrades
* unattended upgrades are only disabled on the officially supported Ubuntu version (at the moment 22.04); do we care if the WG setup playbook fails on an *unsupported* Ubuntu version?

**Comment by MiroslavRepka** [comment]
Hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I just checked the CI and there are still errors.
```
 TASK [./wireguard : Disable unattended (unintended) upgrades] ******************
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [hetzner-control-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    ok: [oci-compute-1]
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [hetzner-compute-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    ok: [oci-control-1]
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [aws-control-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [aws-compute-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
```

Could you take care of that, please?

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf I just checked the CI and there are still errors.
> 
> ```
>  TASK [./wireguard : Disable unattended (unintended) upgrades] ******************
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [hetzner-control-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    ok: [oci-compute-1]
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [hetzner-compute-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    ok: [oci-control-1]
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [aws-control-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
> VPN - services/ansibler/server/clusters/ts3-c-1-s1h1    fatal: [aws-compute-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service unattended-upgrades: host"}
> ```
> 
> Could you take care of that, please?

apparently the service is not present in all images (I only checked GCP).
this can be solved by checking whether the service is present at all before trying to stop it..
good ol' conditions again..
thanks for the review @MiroslavRepka

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
latest changes should make sure it doesn't fail on this, it's first checked that there is anything to disable. it could have been solved by ignoring errors on the task disabling the service, however, now it doesn't run if there is not service, which is a cleaner approach in my opinion.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
alright this is idiotic: I was missing a colon after task `- name`, which is why the whole thing has been failing...should be fixed™ *now*...

**Comment by Despire** [comment]
Hi @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf , there seem to be a bunch of errors, (won't paste the logs here as they're quite large), testing this  on all the test sets at once may no be the best approach, I would suggest a more granular approach, where you deploy claudie localy and try your changes there. You can test one manifest at a time from https://github.com/Berops/claudie/tree/master/manifests/testing-framework/test-sets and see where what breaks

**Review by Despire — APPROVED** [review]
LGTM.

**Pull request merged**
