### PR TITLE
feat: add a security policy file

### LINKED ISSUE #504: Feature: Add a security policy
### Motivation:
As of now, the project is missing a security policy, meaning there is no procedure in place in case of a security incident or should a vulnerability be found in Claudie.

### Description:
Add a security policy to the project.
GitHub's [security policy docs](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).

### Exit criteria:
- [ ] the project has a security policy

### PR DESCRIPTION
**Pull request by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf**
as title, this PR adds a security policy.
fixes #504

### CODE REVIEW

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
the email address listed in the file is, of course, subject to discussion.
any other suggestions are welcome.

**Comment by MarioUhrik** [comment]
A few suggestions, though I am not 100% sure:

- Let's not put this into `docs/claudie-workflow`, I think that's the wrong place. I think https://github.com/Berops/claudie/tree/master/docs/contributing is a good start
- Let's link this from the main README.md, in a similar way as `contributing` is.
- I'd rephrase `If you discover a security issues in this repo` into `If you discover a sensitive security issue in this repo`
- We need to talk about the email address

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Hi guys, I like this. The challenge with the security mailbox is that once we open it wide, we'll start getting some spam. Shall we try it out anyways? We can always tear it down. If so, I'd host it on @berops.com.

spam is always a challenge with email, I agree.

if we go with email then, is security at berops good with you? internally, it could be forwarded on, I was thinking.

**Comment by bernardhalas** [comment]
The `security` label is forwarded to internal group now. Good to merge, IMO.

**Review by bernardhalas — APPROVED** [review]

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
:rocket:

**Pull request merged**
