### PR TITLE
Create own ansible base image

### PR DESCRIPTION
**Pull request by MiroslavRepka**
This PR creates our own ansible base image for `ansibler`, due to issues seen in recent pipeline runs.

### CODE REVIEW

**Comment by MarioUhrik** [comment]
Guys, is there truly no `ansible` image out there that we can use ?
Nothing from here?
https://hub.docker.com/r/ansible/ansible/tags
I see those aren't `arm64` compatible, so fair enough.
But these still are, aren't they?
https://hub.docker.com/r/cytopia/ansible/tags

It sounds absurd to me that we have to create our own Ansible image.
But we can do it if there's no other way, of course.

**Comment by Despire** [comment]
Since this Dockefile is inspired by https://github.com/cytopia/docker-ansible, can't we just use it as the base image ? Like Mario suggested.

**Comment by MiroslavRepka** [comment]
Hi @MarioUhrik 
>https://hub.docker.com/r/ansible/ansible/tags 

The last time this was updated was 5 years ago

>https://hub.docker.com/r/cytopia/ansible/tags

They merge the support for `arm64` [2 days ago](https://github.com/cytopia/docker-ansible/pull/111) FYI @Despire, the reason for this PR was missing support for arm

**Comment by MarioUhrik** [comment]
> The last time this was updated was 5 years ago
You are right, let's not use 5 year old stuff, sorry for suggesting that, I didn't notice

Well, if the issues with `cytopia` are now gone, I'd vote to return to the previous approach :D

**Comment by MiroslavRepka** [comment]
>Well, if the issues with cytopia are now gone, I'd vote to return to the previous approach :D

I am rerunning the CI which failed because of a missing arm image. If that step will succeed now, we can close this.

**Comment by MiroslavRepka** [comment]
Closing due to recent addition of  cytopia's of arm-based images

**Pull request closed without merging**
