### PR TITLE
missing param in example input manifest

### PR DESCRIPTION
**Pull request by katapultcloud**
ERR Skipping over file /input-manifests/manifest.yaml due to processing error : failed to validate nodepools section inside manifest: failed to validate DynamicNodePool "compute-hetzner-autoscaled": Key: 'DynamicNodePool.Count' Error:Field validation for 'Count' failed on the 'required_without' tag module=frontend

### CODE REVIEW

**Comment by MiroslavRepka** [comment]
Hi @katapultcloud, thanks for the PR! The error is correct, although kind of misleading. The real issue is in [here](https://github.com/berops/claudie/blob/docs-patch/docs/input-manifest/example.yaml#L169), it should say `autoscaler`, instead of `autoscalerConf`. I probably left it there while working on the autoscaler feature, apologies for the confusion.

**Comment by MarioUhrik** [comment]
The API docs should be updated too
https://github.com/berops/claudie/blob/master/docs/input-manifest/input-manifest.md#dynamic

**Comment by katapultcloud** [comment]
@MiroslavRepka @MarioUhrik updated.

**Review by MiroslavRepka — APPROVED** [review]
LGTM

**Pull request merged**
