### PR TITLE
Feat/cs ds equality

### PR DESCRIPTION
**Pull request by MiroslavRepka**
This PR fixes the issue described in #370 

The problem was in the `context-box` since it did not update the Desired State after `builder` finished processing. This lead to the difference between these two.

This PR also improves the `printConfig()` function, with a small test to check if the prints are equal for both states.

### CODE REVIEW

**Review by Despire — APPROVED** [review]
LGTM! Thanks for the fix @MiroslavRepka

**Comment by MiroslavRepka** [comment]
@Despire could you please check my latest commits before we merge it?

**Comment by Despire** [comment]
why is the check `if dbConf.DesiredState != nil {`  needed ? shouldn't the config from builder also have desired state set to nil ?

**Comment by MiroslavRepka** [comment]
Thanks for feedback @Despire :) 
>why is the check if dbConf.DesiredState != nil { needed ? shouldn't the config from builder also have desired state set to nil ?

Image a case, where Builder will start building the infra, and while Builder is working, a request for deletion comes. 

The deletion request will set `DesiredState` to `nil` and would wait until the Builder finishes. 

When the Builder is finished we need to save the current state as well as desired state, since Builder updates both of them. So if we would not check, if the config in a database does not have a `DesiredState` set to `nil`, the `SaveConfigBuilder` would overwrite it with the desired state from before the deletion request, resulting in a `DesiredState` not being `nil`, even though it should have been because of the deletion request.

**Comment by Despire** [comment]
thx for the explanation @MiroslavRepka, didn't considered the deletion at all :), 
the changes looks good 👍

**Pull request merged**
