### PR TITLE
Fix/static nodes

### LINKED ISSUE #1141: Bug: Prevent same static node being added to multiple clusters
### Current Behaviour
Currently it seems like nothing prevents the same static node being a part of multiple cluster manifests. We should prevent such a scenario from happening.

### Expected Behaviour
If a node is added into a cluster before it's properly decommissioned from the previous cluster, the operation will not happen until a successful decommissioning is done in the first place. Respective log error message is emitted.

### PR DESCRIPTION
**Pull request by Despire**
Closes #1141 

Check if the same static node is re-used.

1. Within the same config (by tracking the nodepool name)
2. Across different configs (by tracking the IP of every node) No two static nodes can have the same IP, thus if the same IP is used in different config this means the same static node is referenced.

This will work for now, but once https://github.com/berops/claudie/issues/962 is being worked on this should be revisited.

### CODE REVIEW

**Comment by bernardhalas** [comment]
Hi @Despire,
Will this cover also the scenario when a different Claudie instance will try to use a static node which is under control by another Claudie control plane?

**Comment by Despire** [comment]
>Will this cover also the scenario when a different Claudie instance 

Do you mean 2 claudie deployed in two management clusters ? If so they share the same mongoDB then yes, otherwise no.

**Comment by Despire** [comment]
@bernardhalas 

Do you want to implement this ? 'Cause this might be a bigger issue, tracking all of the static nodes across different claudie instances running on different management clusters.

**Comment by bernardhalas** [comment]
> > Will this cover also the scenario when a different Claudie instance

> Do you mean 2 claudie deployed in two management clusters ? If they share the same mongoDB then yes, otherwise no.

Can we have 2 claudie instances that would share the same DB?

> Do you want to implement this ? 'Cause this might be a bigger issue, tracking all of the static nodes across different claudie instances running on different management clusters.

If we had each Claudie instance with its ID, it would be pretty easy to leave a tag on the node saying to which instance it belongs. But I assume it's OK like this for now.

**Comment by Despire** [comment]
> Can we have 2 claudie instances that would share the same DB?

Once this issue https://github.com/berops/claudie/issues/815 is implemented than it would be possible to share a common database.

> If we had each Claudie instance with its ID, it would be pretty easy to leave a tag on the node saying to which instance it belongs. But I assume it's OK like this for now.

I can open an issue about this so we can discuss this further

**Review by cloudziu — APPROVED** [review]

**Pull request merged**
