### PR TITLE
upgrade CONTOLLER_TOOLS_VERSION in Makefile from v0.11.3 to v0.15.0

### PR DESCRIPTION
**Pull request by JKBGIT1**
closes https://github.com/berops/claudie/issues/1423

### CODE REVIEW

**Review by bernardhalas — APPROVED** [review]
LGTM!

**Comment by cloudziu** [comment]
Hey guys, just testes on version `v0.15.0`. Generating manifests itself also worked for me

**Comment by JKBGIT1** [comment]
Thanks @cloudziu :+1: just upgraded.

**Review by Despire — APPROVED** [review]
LGTM

**Pull request merged**
